version: "3.2"
services:
  dev:
    build:
      context: .
      dockerfile: dev.Dockerfile
    image: nir-dev
    volumes:
      - type: bind
        source: ./volumes/dev-home
        target: /home/kda/data
    networks:
      - common
networks:
  common:
    driver: bridge
